/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.application.admin;


import org.civilian.controller.ControllerSignature;


/**
 * Defines the resources of application org.civilian.application.admin.AdminApp.
 */
public interface AdminResources
{
	/**
	 * "/" -&lt; org.civilian.application.admin.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -&lt; org.civilian.application.admin.IndexController
	 */
	public static class Root extends org.civilian.resource.Resource
	{
		public Root()
		{
			super();
			setControllerSignature(sig("", "IndexController"));

			this.$appId = new $AppId(this);
		}

		/**
		 * "/{appId}"
		 */
		public final $AppId $appId;


		/**
		 * "/{appId}"
		 */
		public static class $AppId
		{
			public $AppId(org.civilian.resource.Resource parent)
			{
				this.resource_ = new org.civilian.resource.Resource(parent, org.civilian.application.admin.AdminPathParams.APPID);
				this.resources = new org.civilian.resource.Resource(this.resource_, "resources");
				this.resources.setControllerSignature(sig(".app", "ResourcesController"));
				this.settings = new org.civilian.resource.Resource(this.resource_, "settings");
				this.settings.setControllerSignature(sig(".app", "SettingsController"));
			}

			/**
			 * "/{appId}/resources" -&lt; org.civilian.application.admin.app.ResourcesController
			 */
			public final org.civilian.resource.Resource resources;

			/**
			 * "/{appId}/settings" -&lt; org.civilian.application.admin.app.SettingsController
			 */
			public final org.civilian.resource.Resource settings;

			// hidden since not mapped to a controller
			private final org.civilian.resource.Resource resource_;
		}


		private static ControllerSignature sig(String subPackage, String className)
		{
			return new ControllerSignature("org.civilian.application.admin" + subPackage + '.' + className);
		}
	}
}
