/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.samples.quickstart;


import org.civilian.controller.ControllerSignature;


/**
 * Defines the resources of application org.civilian.samples.quickstart.QsApp.
 */
public interface QsResources
{
	/**
	 * "/" -> org.civilian.samples.quickstart.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> org.civilian.samples.quickstart.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			super();
			setControllerSignature(sig("", "IndexController"));

			this.users = new Users(this);
		}

		/**
		 * "/users" -> org.civilian.samples.quickstart.users.IndexController
		 */
		public final Users users;


		/**
		 * "/users" -> org.civilian.samples.quickstart.users.IndexController
		 */
		public static class Users extends org.civilian.Resource
		{
			public Users(org.civilian.Resource parent)
			{
				super(parent, "users");
				setControllerSignature(sig(".users", "IndexController"));

				this.$userId = new org.civilian.Resource(this, org.civilian.samples.quickstart.QsPathParams.USERID);
				this.$userId.setControllerSignature(sig(".users.id", "IndexController"));
			}

			/**
			 * "/users/{userId}" -> org.civilian.samples.quickstart.users.id.IndexController
			 */
			public final org.civilian.Resource $userId;
		}


		private static ControllerSignature sig(String subPackage, String className)
		{
			return new ControllerSignature("org.civilian.samples.quickstart" + subPackage + '.' + className);
		}
	}
}
