/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.samples.quickstart;


/**
 * Defines the resources of application org.civilian.samples.quickstart.QsApp.
 */
public interface QsResources
{
	/**
	 * "/" -> org.civilian.samples.quickstart.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> org.civilian.samples.quickstart.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			setControllerSignature(cls("", "IndexController"), null);

			this.users = new Users(this);
		}

		/**
		 * "/users" -> org.civilian.samples.quickstart.users.IndexController
		 */
		public final Users users;


		/**
		 * "/users" -> org.civilian.samples.quickstart.users.IndexController
		 */
		public static class Users extends org.civilian.Resource
		{
			public Users(org.civilian.Resource parent)
			{
				super(parent, "users");
				setControllerSignature(cls(".users", "IndexController"), null);

				this.$userId = new org.civilian.Resource(this, org.civilian.samples.quickstart.QsPathParams.USERID);
				this.$userId.setControllerSignature(cls(".users.id", "IndexController"), null);
			}

			/**
			 * "/users/{userId}" -> org.civilian.samples.quickstart.users.id.IndexController
			 */
			public final org.civilian.Resource $userId;
		}


		private static String cls(String subPackage, String className)
		{
			return "org.civilian.samples.quickstart" + subPackage + '.' + className;
		}
	}
}
