/*
 * Copyright (C) 2014 Civilian Framework.
 *
 * Licensed under the Civilian License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.civilian-framework.org/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Generated by org.civilian.tool.resource.ClientConstGenerator.
 * Do not edit.
 */
package org.civilian.client;


/**
 * Resource "/" of application org.civilian.testcase1.Test1App.
 */
public class Test1WebRoot extends org.civilian.client.WebResource
{
	public Test1WebRoot(String url)
	{
		super(url);

		addChild(this.alpha = new org.civilian.client.WebResource(this, "alpha"));
		addChild(this.beta = new Beta(this));
		addChild(this.mixed = new Mixed(this));
		addChild(this.$gammaId = new org.civilian.client.WebResource(this, org.civilian.testcase1.Test1PathParams.GAMMA));
	}

	/**
	 * Resource "/alpha".
	 */
	public final org.civilian.client.WebResource alpha;

	/**
	 * Resource "/beta".
	 */
	public final Beta beta;

	/**
	 * Resource "/mixed".
	 */
	public final Mixed mixed;

	/**
	 * Resource "/{gammaId}".
	 */
	public final org.civilian.client.WebResource $gammaId;


	/**
	 * Resource "/beta".
	 */
	public static class Beta extends org.civilian.client.WebResource
	{
		public Beta(org.civilian.client.WebResource parent)
		{
			super(parent, "beta");

			addChild(this.imspecial = new org.civilian.client.WebResource(this, "imspecial"));
			addChild(this.some = new Some(this));
			addChild(this.$beta = new org.civilian.client.WebResource(this, org.civilian.testcase1.Test1PathParams.BETA));
		}

		/**
		 * Resource "/beta/imspecial".
		 */
		public final org.civilian.client.WebResource imspecial;

		/**
		 * Resource "/beta/some".
		 */
		public final Some some;

		/**
		 * Resource "/beta/{beta}".
		 */
		public final org.civilian.client.WebResource $beta;


		/**
		 * Resource "/beta/some".
		 */
		public static class Some extends org.civilian.client.WebResource
		{
			public Some(org.civilian.client.WebResource parent)
			{
				super(parent, "some");

				addChild(this.thing = new org.civilian.client.WebResource(this, "thing"));
			}

			/**
			 * Resource "/beta/some/thing".
			 */
			public final org.civilian.client.WebResource thing;
		}
	}


	/**
	 * Resource "/mixed".
	 */
	public static class Mixed extends org.civilian.client.WebResource
	{
		public Mixed(org.civilian.client.WebResource parent)
		{
			super(parent, "mixed");

			addChild(this.something = new org.civilian.client.WebResource(this, "something"));
		}

		/**
		 * Resource "/mixed/something".
		 */
		public final org.civilian.client.WebResource something;
	}
}
