/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.internal.admin;


import org.civilian.controller.ControllerSignature;


/**
 * Defines the resources of application org.civilian.internal.admin.AdminApp.
 */
public interface AdminResources
{
	/**
	 * "/" -> org.civilian.internal.admin.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> org.civilian.internal.admin.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			setControllerSignature(sig("", "IndexController"));

			this.$appId = new $AppId(this);
		}

		/**
		 * "/{appId}"
		 */
		public final $AppId $appId;


		/**
		 * "/{appId}"
		 */
		public static class $AppId extends org.civilian.Resource
		{
			public $AppId(org.civilian.Resource parent)
			{
				super(parent, org.civilian.internal.admin.AdminPathParams.APPID);
				this.resources = new org.civilian.Resource(this, "resources");
				this.resources.setControllerSignature(sig(".app", "ResourcesController"));
				this.settings = new org.civilian.Resource(this, "settings");
				this.settings.setControllerSignature(sig(".app", "SettingsController"));
			}

			/**
			 * "/{appId}/resources" -> org.civilian.internal.admin.app.ResourcesController
			 */
			public final org.civilian.Resource resources;

			/**
			 * "/{appId}/settings" -> org.civilian.internal.admin.app.SettingsController
			 */
			public final org.civilian.Resource settings;
		}


		private static ControllerSignature sig(String subPackage, String className)
		{
			return new ControllerSignature("org.civilian.internal.admin" + subPackage + '.' + className);
		}
	}
}
