/**
 * Generated by org.civilian.resource.scan.ResourceScan.
 * Do not edit.
 */
package !{webPackage};


/**
 * Defines the resources of application !{webPackage}.!{appPrefix}App.
 */
public interface !{appPrefix}Resources
{
	/**
	 * The root resource.
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> !{webPackage}.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			super();
			setControllerSignature("!{webPackage}.IndexController");

			this.users = new Users(this);
		}

		/**
		 * "/users" -> !{webPackage}.users.IndexController
		 */
		public final Users users;


		/**
		 * "/users" -> !{webPackage}.users.IndexController
		 */
		public static class Users extends org.civilian.Resource
		{
			public Users(org.civilian.Resource parent)
			{
				super(parent, "users");
				setControllerSignature("!{webPackage}.users.IndexController");
				
				this.$userId = new org.civilian.Resource(this, !{webPackage}.!{appPrefix}PathParams.USERID);
				this.$userId.setControllerSignature("!{webPackage}.users.id.IndexController");
			}

			/**
			 * "/users/{userId}" -> !{webPackage}.users.id.IndexController
			 */
			public final org.civilian.Resource $userId;
		}
	}
}
