/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.samples.crm.web;


import org.civilian.controller.ControllerSignature;


/**
 * Defines the resources of application org.civilian.samples.crm.web.CrmApp.
 */
public interface CrmResources
{
	/**
	 * "/" -> org.civilian.samples.crm.web.root.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> org.civilian.samples.crm.web.root.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			setControllerSignature(sig("", "IndexController"));

			this.contacts = new Contacts(this);
			this.customers = new Customers(this);
			this.login = new org.civilian.Resource(this, "login");
			this.login.setControllerSignature(sig("", "LoginController"));
			this.logout = new org.civilian.Resource(this, "logout");
			this.logout.setControllerSignature(sig("", "LogoutController"));
			this.opportunities = new Opportunities(this);
			this.users = new Users(this);
		}

		/**
		 * "/contacts" -> org.civilian.samples.crm.web.root.contacts.IndexController
		 */
		public final Contacts contacts;

		/**
		 * "/customers" -> org.civilian.samples.crm.web.root.customers.IndexController
		 */
		public final Customers customers;

		/**
		 * "/login" -> org.civilian.samples.crm.web.root.LoginController
		 */
		public final org.civilian.Resource login;

		/**
		 * "/logout" -> org.civilian.samples.crm.web.root.LogoutController
		 */
		public final org.civilian.Resource logout;

		/**
		 * "/opportunities" -> org.civilian.samples.crm.web.root.opportunities.IndexController
		 */
		public final Opportunities opportunities;

		/**
		 * "/users" -> org.civilian.samples.crm.web.root.users.IndexController
		 */
		public final Users users;


		/**
		 * "/contacts" -> org.civilian.samples.crm.web.root.contacts.IndexController
		 */
		public static class Contacts extends org.civilian.Resource
		{
			public Contacts(org.civilian.Resource parent)
			{
				super(parent, "contacts");
				setControllerSignature(sig(".contacts", "IndexController"));

				this.search = new Search(this);
				this.$contactId = new org.civilian.Resource(this, org.civilian.samples.crm.web.CrmPathParams.CONTACTID);
				this.$contactId.setControllerSignature(sig(".contacts.id", "IndexController"));
			}

			/**
			 * "/contacts/search" -> org.civilian.samples.crm.web.root.contacts.SearchController
			 */
			public final Search search;

			/**
			 * "/contacts/{contactId}" -> org.civilian.samples.crm.web.root.contacts.id.IndexController
			 */
			public final org.civilian.Resource $contactId;


			/**
			 * "/contacts/search" -> org.civilian.samples.crm.web.root.contacts.SearchController
			 */
			public static class Search extends org.civilian.Resource
			{
				public Search(org.civilian.Resource parent)
				{
					super(parent, "search");
					setControllerSignature(sig(".contacts", "SearchController"));

					this.filter = new org.civilian.Resource(this, "filter");
					this.filter.setControllerSignature(sig(".contacts", "SearchController").withMethodSegment("filter"));
				}

				/**
				 * "/contacts/search/filter" -> org.civilian.samples.crm.web.root.contacts.SearchController:filter
				 */
				public final org.civilian.Resource filter;
			}
		}


		/**
		 * "/customers" -> org.civilian.samples.crm.web.root.customers.IndexController
		 */
		public static class Customers extends org.civilian.Resource
		{
			public Customers(org.civilian.Resource parent)
			{
				super(parent, "customers");
				setControllerSignature(sig(".customers", "IndexController"));

				this.lookup = new org.civilian.Resource(this, "lookup");
				this.lookup.setControllerSignature(sig(".customers", "LookupController"));
				this.navigation = new org.civilian.Resource(this, "navigation");
				this.navigation.setControllerSignature(sig(".customers", "NavigationController"));
				this.search = new Search(this);
				this.$customerId = new $CustomerId(this);
			}

			/**
			 * "/customers/lookup" -> org.civilian.samples.crm.web.root.customers.LookupController
			 */
			public final org.civilian.Resource lookup;

			/**
			 * "/customers/navigation" -> org.civilian.samples.crm.web.root.customers.NavigationController
			 */
			public final org.civilian.Resource navigation;

			/**
			 * "/customers/search" -> org.civilian.samples.crm.web.root.customers.SearchController
			 */
			public final Search search;

			/**
			 * "/customers/{customerId}" -> org.civilian.samples.crm.web.root.customers.id.IndexController
			 */
			public final $CustomerId $customerId;


			/**
			 * "/customers/search" -> org.civilian.samples.crm.web.root.customers.SearchController
			 */
			public static class Search extends org.civilian.Resource
			{
				public Search(org.civilian.Resource parent)
				{
					super(parent, "search");
					setControllerSignature(sig(".customers", "SearchController"));

					this.filter = new org.civilian.Resource(this, "filter");
					this.filter.setControllerSignature(sig(".customers", "SearchController").withMethodSegment("filter"));
				}

				/**
				 * "/customers/search/filter" -> org.civilian.samples.crm.web.root.customers.SearchController:filter
				 */
				public final org.civilian.Resource filter;
			}


			/**
			 * "/customers/{customerId}" -> org.civilian.samples.crm.web.root.customers.id.IndexController
			 */
			public static class $CustomerId extends org.civilian.Resource
			{
				public $CustomerId(org.civilian.Resource parent)
				{
					super(parent, org.civilian.samples.crm.web.CrmPathParams.CUSTOMERID);
					setControllerSignature(sig(".customers.id", "IndexController"));

					this.details = new org.civilian.Resource(this, "details");
					this.details.setControllerSignature(sig(".customers.id", "DetailsController"));
					this.masterdata = new org.civilian.Resource(this, "masterdata");
					this.masterdata.setControllerSignature(sig(".customers.id", "MasterdataController"));
				}

				/**
				 * "/customers/{customerId}/details" -> org.civilian.samples.crm.web.root.customers.id.DetailsController
				 */
				public final org.civilian.Resource details;

				/**
				 * "/customers/{customerId}/masterdata" -> org.civilian.samples.crm.web.root.customers.id.MasterdataController
				 */
				public final org.civilian.Resource masterdata;
			}
		}


		/**
		 * "/opportunities" -> org.civilian.samples.crm.web.root.opportunities.IndexController
		 */
		public static class Opportunities extends org.civilian.Resource
		{
			public Opportunities(org.civilian.Resource parent)
			{
				super(parent, "opportunities");
				setControllerSignature(sig(".opportunities", "IndexController"));

				this.search = new Search(this);
				this.$opportunityId = new org.civilian.Resource(this, org.civilian.samples.crm.web.CrmPathParams.OPPORTUNITYID);
				this.$opportunityId.setControllerSignature(sig(".opportunities.id", "IndexController"));
			}

			/**
			 * "/opportunities/search" -> org.civilian.samples.crm.web.root.opportunities.SearchController
			 */
			public final Search search;

			/**
			 * "/opportunities/{opportunityId}" -> org.civilian.samples.crm.web.root.opportunities.id.IndexController
			 */
			public final org.civilian.Resource $opportunityId;


			/**
			 * "/opportunities/search" -> org.civilian.samples.crm.web.root.opportunities.SearchController
			 */
			public static class Search extends org.civilian.Resource
			{
				public Search(org.civilian.Resource parent)
				{
					super(parent, "search");
					setControllerSignature(sig(".opportunities", "SearchController"));

					this.filter = new org.civilian.Resource(this, "filter");
					this.filter.setControllerSignature(sig(".opportunities", "SearchController").withMethodSegment("filter"));
				}

				/**
				 * "/opportunities/search/filter" -> org.civilian.samples.crm.web.root.opportunities.SearchController:filter
				 */
				public final org.civilian.Resource filter;
			}
		}


		/**
		 * "/users" -> org.civilian.samples.crm.web.root.users.IndexController
		 */
		public static class Users extends org.civilian.Resource
		{
			public Users(org.civilian.Resource parent)
			{
				super(parent, "users");
				setControllerSignature(sig(".users", "IndexController"));

				this.search = new Search(this);
				this.$userId = new org.civilian.Resource(this, org.civilian.samples.crm.web.CrmPathParams.USERID);
				this.$userId.setControllerSignature(sig(".users.id", "IndexController"));
			}

			/**
			 * "/users/search" -> org.civilian.samples.crm.web.root.users.SearchController
			 */
			public final Search search;

			/**
			 * "/users/{userId}" -> org.civilian.samples.crm.web.root.users.id.IndexController
			 */
			public final org.civilian.Resource $userId;


			/**
			 * "/users/search" -> org.civilian.samples.crm.web.root.users.SearchController
			 */
			public static class Search extends org.civilian.Resource
			{
				public Search(org.civilian.Resource parent)
				{
					super(parent, "search");
					setControllerSignature(sig(".users", "SearchController"));

					this.filter = new org.civilian.Resource(this, "filter");
					this.filter.setControllerSignature(sig(".users", "SearchController").withMethodSegment("filter"));
				}

				/**
				 * "/users/search/filter" -> org.civilian.samples.crm.web.root.users.SearchController:filter
				 */
				public final org.civilian.Resource filter;
			}
		}


		private static ControllerSignature sig(String subPackage, String className)
		{
			return new ControllerSignature("org.civilian.samples.crm.web.root" + subPackage + '.' + className);
		}
	}
}
