/*
 * Copyright (C) 2014 Civilian Framework.
 *
 * Licensed under the Civilian License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.civilian-framework.org/license.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.civilian.samples.client;


import org.civilian.client.WebUrl;
import org.civilian.samples.crm.web.CrmPathParams;


/**
 * Demonstrates the use of org.civilian.client.
 */
public class Client
{
	public static void main(String[] args)
	{
		// CrmRoot is generated by org.civilian.client.gen.ResourceGenerator
		// from the crm resource tree
		CrmRoot root = new CrmRoot("http://localhost/civilian/crm");
		
		// resources are accessed via constants
		System.out.println("Masterdata route:");
		System.out.println(root.customers.$customerId.masterdata);
		
		// WebUrl helps to create complex urls
		WebUrl url = new WebUrl(root.customers.$customerId.masterdata)
			.setPathParam(CrmPathParams.CUSTOMERID, 15)
			.addQueryParam("reload", true)
			.addQueryParam("time", 20120102)
			.setFragment("fragment");
		System.out.println();
		System.out.println("Masterdata url:");
		System.out.println(url);
		
		// urls can be reused:
		url.setPathParam(CrmPathParams.CUSTOMERID, 16).clearQueryParams();
		System.out.println();
		System.out.println("Masterdata url now:");
		System.out.println(url);
	}
}
