/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.samples.jpa.jta;


/**
 * Defines the resources of application org.civilian.samples.jpa.jta.JtaApp.
 */
public interface JtaResources
{
	/**
	 * "/" -> org.civilian.samples.jpa.jta.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" -> org.civilian.samples.jpa.jta.IndexController
	 */
	public static class Root extends org.civilian.Resource
	{
		public Root()
		{
			setControllerSignature(cls("", "IndexController"), null);

			this.create = new org.civilian.Resource(this, "create");
			this.create.setControllerSignature(cls("", "CreateController"), null);
		}

		/**
		 * "/create" -> org.civilian.samples.jpa.jta.CreateController
		 */
		public final org.civilian.Resource create;


		private static String cls(String subPackage, String className)
		{
			return "org.civilian.samples.jpa.jta" + subPackage + '.' + className;
		}
	}
}
