/**
 * Generated by org.civilian.tool.resource.ServerConstGenerator.
 * Do not edit.
 */
package org.civilian.samples.jpa.jta;


import org.civilian.controller.ControllerSignature;
import org.civilian.controller.ControllerResourceData;


/**
 * Defines the resources of application org.civilian.samples.jpa.jta.JtaApp.
 */
public interface JtaResources
{
	/**
	 * "/" = org.civilian.samples.jpa.jta.IndexController
	 */
	public static final Root root = new Root();


	/**
	 * "/" = org.civilian.samples.jpa.jta.IndexController
	 */
	public static class Root extends org.civilian.resource.Resource
	{
		public Root()
		{
			super();
			setData(data(sig("", "IndexController")));

			this.create = new org.civilian.resource.Resource(this, "create");
			this.create.setData(data(sig("", "CreateController")));
		}

		/**
		 * "/create" = org.civilian.samples.jpa.jta.CreateController
		 */
		public final org.civilian.resource.Resource create;


		private static ControllerSignature sig(String subPackage, String className)
		{
			return new ControllerSignature("org.civilian.samples.jpa.jta" + subPackage + '.' + className);
		}


		private static ControllerResourceData data(ControllerSignature sig)
		{
			return new ControllerResourceData(sig);
		}
	}
}
